---
all:
  vars:
    ansible_user: root
    ansible_become: false

  children:
    targets:
      hosts:
        node1:
          ansible_host: rhel01.nostromo.io
          node_role: target_fleet
          environment_type: production
        node3:
          ansible_host: rhel03.nostromo.io
          node_role: target_fleet
          environment_type: production
        node4:
          ansible_host: rhel04.nostromo.io
          node_role: target_fleet
          environment_type: staging

    builders:
      hosts:
        node2:
          ansible_host: rhel02.nostromo.io
          node_role: rhtpa_builder
          rhtpa_enabled: true

    eda:
      hosts:
        controller:
          ansible_host: aap.nostromo.io
          ansible_connection: local
