---
all:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_ssh_private_key_file: "{{ vault_ssh_key_path }}"

  children:
    targets:
      hosts:
        node1:
          ansible_host: "{{ vault_node1_host }}"
          node_role: target_fleet
          environment_type: production

    builders:
      hosts:
        node2:
          ansible_host: "{{ vault_node2_host }}"
          node_role: rhtpa_builder
          rhtpa_enabled: true

    eda:
      hosts:
        controller:
          ansible_host: "{{ vault_controller_host }}"
          ansible_connection: local
