---
collections:
  - name: redhat.trusted_profile_analyzer
  - name: ansible.eda
  - name: ansible.platform
  - name: redhat.rhel_system_roles
  - name: community.general
  - name: ansible.posix
  - name: containers.podman
